// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID              uuid.UUID     `json:"id"`
	Body            string        `json:"body"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
	UserID          uuid.UUID     `json:"user_id"`
	PostID          uuid.UUID     `json:"post_id"`
	ParentCommentID uuid.NullUUID `json:"parent_comment_id"`
}

type Follower struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FollowesID uuid.UUID `json:"followes_id"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UserID    uuid.UUID `json:"user_id"`
}

type Post struct {
	ID        uuid.UUID    `json:"id"`
	Body      string       `json:"body"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
}

type PostLike struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	Username           string         `json:"username"`
	Email              string         `json:"email"`
	HashedPassword     string         `json:"hashed_password"`
	Bio                sql.NullString `json:"bio"`
	HashedRefreshToken sql.NullString `json:"hashed_refresh_token"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}
